---
name: production

on:
  push:
    branches: [production]
    paths-ignore:
      - README.md
      - .trunk
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get current date
        run: echo "DATE=$(date +'%Y.%m.%d')" >> "$GITHUB_ENV"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ env.DATE }}-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Send Discord notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          title: "Build image on ${{ github.repository }}: ${{ github.workflow }}"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}